const E=require('./dist/engine.js'),fs=require('node:fs'),assert=require('node:assert/strict');
const empty={seed:0,planets:[]};
function fly(b,world=empty,r=48){let s=E.create(b,world);while(s.state==='flying')E.step(s,E.DT,r);assert(s.t<=30.0001);return s;}
const checks=[];function check(name,fn){fn();checks.push({name,result:'PASS'});}
check('No cockpit cannot create flight',()=>assert.throws(()=>E.create([{x:0,y:0,type:'body'},{x:1,y:0,type:'engine',dir:'up',start:0,end:2}],empty),/조종석/));
check('Three collinear engines merge into one 108 kN engine',()=>{let b=[{x:3,y:3,type:'cockpit'},...[0,1,2].map(x=>({x,y:3,type:'engine',dir:'right',start:0,end:1}))];assert.equal(E.groups(b).length,1);assert.equal(E.groups(b)[0].n,3);let s=E.create(b,empty);E.step(s);assert.equal(s.thrust,108);assert.equal(s.active,1);assert(Math.abs(s.omega)<1e-12);assert(Math.abs(s.vx-108/5*E.DT)<1e-10);});
check('Merged engines share time; deletion splits the chain',()=>{let b=[0,1,2].map(x=>({x,y:3,type:'engine',dir:'up',start:x,end:x+3}));E.syncGroups(b);assert(b.every(m=>m.start===0&&m.end===3));b.splice(1,1);assert.equal(E.groups(b).length,2);});
check('L-shaped engines do not form a single merged engine',()=>{assert.equal(E.groups([{x:0,y:0,type:'engine',dir:'up'},{x:1,y:0,type:'engine',dir:'up'},{x:0,y:1,type:'engine',dir:'up'}]).length,2);});
check('Lower lateral thrust produces clockwise-screen negative torque and angular inertia',()=>{let b=[{x:4,y:2,type:'cockpit'},{x:4,y:3,type:'body'},{x:4,y:4,type:'engine',dir:'right',start:0,end:.5}],s=E.create(b,empty);for(let i=0;i<120;i++)E.step(s);assert(s.angle<-.01);assert(s.omega<0);const omega=s.omega;E.step(s);assert.equal(s.omega,omega);assert(Math.abs(s.vy)>0);});
check('Symmetric forces cancel torque and balanced example can win',()=>{let s=fly(E.example());assert.equal(s.state,'success');assert.equal(s.angle,0);});
check('Seeded random worlds vary, preview and moving collision geometry agree',()=>{assert.deepEqual(E.makeWorld(100),E.makeWorld(100));assert.notDeepEqual(E.makeWorld(100),E.makeWorld(101));let worlds=Array.from({length:30},(_,i)=>E.makeWorld(i+10));assert(worlds.some(w=>w.planets.some(p=>p.vx||p.vy)));assert(new Set(worlds.flatMap(w=>w.planets.map(p=>p.points.length))).size>=3);let moving=worlds.flatMap(w=>w.planets).find(p=>p.vx||p.vy);assert.notDeepEqual(E.planetAt(moving,0),E.planetAt(moving,1));let world=E.makeWorld(91),s=E.create(E.example(),world);assert.deepEqual(s.world,world);});
check('Polygon edge contact collides; rotated rectangles use real corners',()=>{const box=[{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10}];assert(E.overlap(box,box.map(p=>({x:p.x+10,y:p.y}))));assert(!E.overlap(box,box.map(p=>({x:p.x+11,y:p.y}))));let s=E.create(E.example(),empty),m=s.b[0],a=E.corners(s,m);s.angle=Math.PI/4;assert.notDeepEqual(a,E.corners(s,m));});
check('Actual ship/planet collision ends flight',()=>{const p={x:260,y:400,r:50,vx:0,vy:0,points:[{x:-60,y:-60},{x:60,y:-60},{x:60,y:60},{x:-60,y:60}]};let b=[{x:3,y:3,type:'engine',dir:'right',start:0,end:20},{x:4,y:3,type:'cockpit'},{x:5,y:3,type:'engine',dir:'right',start:0,end:20}];assert.match(fly(b,{seed:0,planets:[p]}).reason,/충돌/);});
check('Timeout and disconnected spacecraft reject correctly',()=>{let b=E.example();b.filter(m=>m.type==='engine').forEach(m=>{m.start=29;m.end=29.1;});assert.equal(fly(b).t,30);b.push({x:0,y:0,type:'body'});assert.match(E.valid(b),/연결/);});
let records=[];for(const radius of [28,48])for(let i=0;i<10;i++){let b=E.example();b.filter(m=>m.type==='engine'&&m.dir==='up').forEach(m=>m.end=+(1.3+i*.05).toFixed(2));const seed=100+i,world=E.makeWorld(seed),s=fly(b,world,radius);records.push({group:radius===28?'before':'after',trial:i+1,goalRadius:radius,upEnd:b.find(m=>m.dir==='up').end,seed,score:s.state==='success'?100:0,time:+s.t.toFixed(4),result:s.state,reason:s.reason});}
const median=a=>{a=a.slice().sort((a,b)=>a-b);return(a[4]+a[5])/2;};const summaries=[28,48].map(r=>{let a=records.filter(x=>x.goalRadius===r);return {radius:r,wins:a.filter(x=>x.result==='success').length,medianSeconds:median(a.map(x=>x.time)),minSeconds:Math.min(...a.map(x=>x.time)),maxSeconds:Math.max(...a.map(x=>x.time))};});
fs.writeFileSync('dist/difficulty-records.json',JSON.stringify({version:2,method:'회전 물리·무작위 행성 버전 자동 플레이. 두 묶음에 같은 10개 seed와 같은 10개 설계를 사용. 난이도는 목표 반경 28→48 하나만 변경.',fixed:{force:36,timeLimit:30,dt:E.DT,worldSeeds:'100~109',rightEngine:[3,9]},records,summaries},null,2));fs.writeFileSync('dist/physics-verification.json',JSON.stringify({version:2,checks},null,2));console.log(JSON.stringify({checks,summaries},null,2));
