const E=require('./dist/engine.js'),fs=require('node:fs'),assert=require('node:assert/strict');
const empty={seed:0,planets:[],storms:[],goal:{...E.GOAL}};
const checks=[];function check(name,fn){fn();checks.push({name,result:'PASS'});}
check('조종석 없이는 발사 불가',()=>assert.match(E.valid([{x:0,y:0,type:'body'},{x:1,y:0,type:'engine',dir:'up',start:0,end:2}]),/조종석/));
check('동체 없이는 발사 불가',()=>assert.match(E.valid([{x:0,y:0,type:'cockpit'},{x:1,y:0,type:'engine',dir:'up',start:0,end:2}]),/동체/));
check('일렬 엔진 3개는 108 kN 한 묶음',()=>{let b=[...[0,1,2].map((x,i)=>({x,y:3,type:'engine',engineId:i+1,dir:'right',start:0,end:1})),{x:3,y:3,type:'body'},{x:4,y:3,type:'cockpit'}];assert.equal(E.groups(b).length,1);assert.equal(E.groups(b)[0].n,3);let s=E.create(b,empty);E.step(s);assert.equal(s.thrust,108);assert.equal(s.active,1);assert(Math.abs(s.omega)<1e-12);assert(Math.abs(s.vx-108/6*E.DT)<1e-10);});
check('병합 엔진 시간 공유와 삭제 후 분리',()=>{let b=[0,1,2].map(x=>({x,y:3,type:'engine',dir:'up',start:x,end:x+3}));E.syncGroups(b);assert(b.every(m=>m.start===0&&m.end===3));b.splice(1,1);assert.equal(E.groups(b).length,2);});
check('L자 엔진은 한 묶음이 아님',()=>assert.equal(E.groups([{x:0,y:0,type:'engine',dir:'up'},{x:1,y:0,type:'engine',dir:'up'},{x:0,y:1,type:'engine',dir:'up'}]).length,2));
check('십자키 전체 이동과 경계 이탈 취소',()=>{const b=[{x:1,y:1,type:'cockpit'},{x:1,y:2,type:'body'},{x:1,y:3,type:'engine',dir:'up',start:0,end:1}],before=JSON.stringify(b);assert(E.moveAll(b,1,0));assert.deepEqual(b.map(m=>m.x),[2,2,2]);while(E.moveAll(b,-1,0));const edge=JSON.stringify(b);assert.equal(E.moveAll(b,-1,0),false);assert.equal(JSON.stringify(b),edge);assert.notEqual(edge,before);});
check('질량중심에서 벗어난 측면 추력은 회전 관성 생성',()=>{let b=[{x:4,y:2,type:'cockpit'},{x:4,y:3,type:'body'},{x:4,y:4,type:'engine',dir:'right',start:0,end:.5}],s=E.create(b,empty);for(let i=0;i<120;i++)E.step(s);assert(s.angle<-.01&&s.omega<0);const omega=s.omega;E.step(s);assert.equal(s.omega,omega);});
check('대칭 예시 설계는 자체 토크가 0',()=>{let s=E.create(E.example(),empty);for(let i=0;i<600;i++)E.step(s);assert(Math.abs(s.angle)<1e-12);});
check('목표·행성·폭풍은 seed 기반 무작위 생성',()=>{assert.deepEqual(E.makeWorld(100),E.makeWorld(100));assert.notDeepEqual(E.makeWorld(100),E.makeWorld(101));const worlds=Array.from({length:30},(_,i)=>E.makeWorld(i+10));assert(new Set(worlds.map(w=>w.goal.x.toFixed(3)+','+w.goal.y.toFixed(3))).size>20);assert(worlds.every(w=>w.goal.r===24));assert(worlds.some(w=>w.planets.some(p=>p.vx||p.vy)));});
check('목표 판정은 각 맵의 무작위 목표를 사용',()=>{const goal={x:730,y:260,r:24},world={seed:1,planets:[],storms:[],goal},s=E.create(E.example(),world),cockpit=s.b.find(m=>m.type==='cockpit'),cp=E.transform(s,cockpit.x*E.CELL,cockpit.y*E.CELL);s.x+=goal.x-cp.x;s.y+=goal.y-cp.y;E.step(s);assert.equal(s.state,'success');});
check('행성 충돌과 30초 종료 판정',()=>{const p={x:260,y:400,r:50,vx:0,vy:0,mass:0,points:[{x:-60,y:-60},{x:60,y:-60},{x:60,y:60},{x:-60,y:60}]};let b=[{x:3,y:3,type:'engine',dir:'right',start:0,end:20},{x:4,y:3,type:'body'},{x:5,y:3,type:'cockpit'}],s=E.create(b,{seed:0,planets:[p],storms:[],goal:{...E.GOAL}});while(s.state==='flying')E.step(s);assert.match(s.reason,/충돌/);b=E.example();b.filter(m=>m.type==='engine').forEach(m=>{m.start=29;m.end=29.1;});s=E.create(b,empty);while(s.state==='flying')E.step(s);assert.equal(s.t,30);});
fs.writeFileSync('dist/physics-verification.json',JSON.stringify({version:3,checks},null,2));
console.log(JSON.stringify({checks},null,2));
